FROM ubuntu:20.04

RUN apt-get update && apt-get -y upgrade && DEBIAN_FRONTEND=noninteractive apt-get install -y \
  awscli \
  rsync \
  git \
  zip \
  unzip \
  wget \
  curl \
  openssh-client \
  php-cli \
  php-zip \
  php-xml \
  php-tokenizer \
  php-mbstring \
  php-curl \
  php7.4-bcmath php7.4-mbstring php7.4-json php7.4-mysql \
  rsync \
 && rm -rf /var/lib/apt/lists/*

RUN mkdir ~/.ssh/ && touch ~/.ssh/known_hosts && ssh-keyscan -p 10022 git.jacob.de >> ~/.ssh/known_hosts
COPY install_composer2.sh install_composer2.sh
RUN /bin/bash install_composer2.sh